# Generated by Django 5.2.8 on 2025-11-19 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(help_text='ID карты из официального Clash Royale API', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_evolution_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_star_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('icon_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('mode', models.CharField(blank=True, max_length=50)),
                ('avg_elixir', models.FloatField(blank=True, null=True)),
                ('win_rate', models.FloatField(blank=True, null=True)),
                ('avg_crowns', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Позиция карты в колоде (0–7)')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_decks', to='app.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='app.deck')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('deck', 'position')},
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='decks', through='app.DeckCard', to='app.card'),
        ),
    ]
