# Generated by Django 5.2.8 on 2025-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='name',
        ),
        migrations.AlterField(
            model_name='card',
            name='api_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='deckcard',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
