global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: deck_collector
    static_configs:
      - targets: ['collector-worker:9100']
        labels:
          service: deck_collector
